website_controllers:
    resource:
        path: ../src/Infrastructure/Controller/Website
        namespace: App\Infrastructure\Controller\Website
    type: attribute

api_doc:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

api_controllers:
    resource:
        path: ../src/Infrastructure/Controller/Api
        namespace: App\Infrastructure\Controller\Api
    prefix: /api
    type: attribute

