admin_controllers:
    resource:
        path: ../src/Infrastructure/Controller/Admin
        namespace: App\Infrastructure\Controller\Admin
    prefix: /admin
    type: attribute
    schemes: ['%url_scheme%']
    host: '%host_website%'

api_controllers:
    resource:
        path: ../src/Infrastructure/Controller/API
        namespace: App\Infrastructure\Controller\API
    prefix: /api
    type: attribute
    schemes: ['%url_scheme%']
    host: '%host_api%'

website_controllers:
    resource:
        path: ../src/Infrastructure/Controller/Website
        namespace: App\Infrastructure\Controller\Website
    type: attribute
    schemes: ['%url_scheme%']
    host: '%host_website%'




