website_controllers:
    resource:
        path: ../src/Infrastructure/Controller/Website
        namespace: App\Infrastructure\Controller\Website
    type: attribute

api_controllers:
    resource:
        path: ../src/Infrastructure/Controller/Api
        namespace: App\Infrastructure\Controller\Api
    prefix: /api
    type: attribute
