website_controllers:
    resource:
        path: ../src/Infrastructure/Website/Controller/
        namespace: App\Infrastructure\Website\Controller
    type: attribute

api_controllers:
    resource:
        path: ../src/Infrastructure/Api/Controller/
        namespace: App\Infrastructure\Api\Controller
    prefix: /api
    type: attribute
